/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    media: Media;
    users: User;
    examples: Example;
  };
  globals: {};
}
export interface Page {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Example {
  id: string;
  text?: string;
  textarea?: string;
  richtext?: {
    [k: string]: unknown;
  }[];
  array?: {
    text?: string;
    id?: string;
  }[];
  blocks?: {
    text?: string;
    id?: string;
    blockName?: string;
    blockType: 'block';
  }[];
  updatedAt: string;
  createdAt: string;
}
